configMapGenerator:
- behavior: merge
  files:
  - values.yaml=configmap.yaml
  name: environment

resources:
- ../base

patches:
- patch: |-
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    metadata:
      name: bigbang
    spec:
      interval: 1m
  # Use the following three lines to test a new version of Big Bang without affecting other environments
  #   ref:
  #     $patch: replace
  #     tag: 2.47.0
- patch: |-
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      name: bigbang
    spec:
      interval: 1m

