apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: registry1
  namespace: bigbang
spec:
  interval: 1m
  type: oci
  url: oci://registry1.dso.mil/bigbang
  secretRef:
    name: private-registry
